language: java
dist: trusty
notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "Commit message: %{commit_message}"
    secure: XdfaIQMLevWXrCtxJ/IY5n+XfGl35VG/ZCsitu41FiQN2V4QmK96YIVAmrc5HiTRCvLCI/HKke9IYZH+5M0n1sG82v9Q4vDmCYfAKI4QbRm6UCgV7Cegb+o0jNQqiA530TUyKqhZzVCvR9H2i7XqkzAa+wNclG9bSv6nYl4iPXrgCJI/hVHainr797gq6HdPH4ajEHX2lnZV9+j+db/EJKhkSDJsS3c8GKhroxfmT8jCeot67JzSihVxI5E2z+reLS+L3Amfb6Dp4srZzYyAj6etsbDNczqODEHfoZRbP2dP0a3o3BuqQUCzW8iBiHstlJiC2YmqZHqVR6IPmWP8eJcL8ni2tPIt11w/v+mAEnAvha9Qa6iT0KrQ7i5LQWgPyVxZCJ/fb3BS4stWc1QNxClV17cEM16aTzPli5isjCI7sbfZF6EzYkW9+XQIe+VuVRg/1vzo0TaQ1qE864BGv3Yjbcerc5LZH/KzkqZy03nKmgC0vz9R9e5AdslLBoC5LgW184AVf9iIbWtEq8/YmZiPrUqV3sTwMmSlHGLGlzcVSvdPsZy5w1PVIQ0cNdDpkMqlJrIk0X8yNQ5KYi/OPJEBUNdYz+FHZUPSpGqw7HFEkFoJe+S4fjiw/KGEAOl/c6PBSOCDSz7RtWeLJ5QuS6r9hJsC0Evvw4/5lGCMzDo=
