name: GitHub CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '13' ]
    name: Java ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-jdk${{ matrix.java }}-
    - name: Build with Maven
      run: mvn -B clean install

    # Slack Notify Build action, see https://github.com/marketplace/actions/slack-notify-build
    # create a Slack bot token as described in https://github.com/marketplace/actions/post-slack-message
    # i.e. go to https://api.slack.com/apps and create a new App, create a bot user, then install the App
    # create a new GitHub repo secret named SLACK_BOT_TOKEN at https://github.com/martin-kuba/example-webapp/settings/secrets
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: D43QWSA5N
        status: SUCCESS
        color: good
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: D43QWSA5N
        status: FAILED
        color: danger
